# =================================================
# Configuración para text_extractor.py
# =================================================

pdfs:
  paths:
    - chatbot-emociones/data/pdfs/Marianela.pdf
